name: loan_simulator
description: Flutter training project. Loan Calculator
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  device_info_plus: ^9.1.2
  geolocator: ^11.0.0
  dio: ^5.4.2
  internet_connection_checker: ^1.0.0+1
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.10
  freezed: ^2.4.7
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  collection: ^1.17.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
